/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatRole } from './ChatRole';
import {
    ChatRoleFromJSON,
    ChatRoleFromJSONTyped,
    ChatRoleToJSON,
} from './ChatRole';

/**
 * 
 * @export
 * @interface ChatMessage
 */
export interface ChatMessage {
    /**
     * 
     * @type {ChatRole}
     * @memberof ChatMessage
     */
    role: ChatRole;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    content: string;
}

/**
 * Check if a given object implements the ChatMessage interface.
 */
export function instanceOfChatMessage(value: object): boolean {
    if (!('role' in value)) return false;
    if (!('content' in value)) return false;
    return true;
}

export function ChatMessageFromJSON(json: any): ChatMessage {
    return ChatMessageFromJSONTyped(json, false);
}

export function ChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'role': ChatRoleFromJSON(json['role']),
        'content': json['content'],
    };
}

export function ChatMessageToJSON(value?: ChatMessage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role': ChatRoleToJSON(value['role']),
        'content': value['content'],
    };
}

