/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
} from './ChatMessage';
import type { FinishReason } from './FinishReason';
import {
    FinishReasonFromJSON,
    FinishReasonFromJSONTyped,
    FinishReasonToJSON,
} from './FinishReason';

/**
 * 
 * @export
 * @interface Choice
 */
export interface Choice {
    /**
     * 
     * @type {FinishReason}
     * @memberof Choice
     */
    finishReason: FinishReason;
    /**
     * 
     * @type {number}
     * @memberof Choice
     */
    index: number;
    /**
     * 
     * @type {ChatMessage}
     * @memberof Choice
     */
    message: ChatMessage;
}

/**
 * Check if a given object implements the Choice interface.
 */
export function instanceOfChoice(value: object): boolean {
    if (!('finishReason' in value)) return false;
    if (!('index' in value)) return false;
    if (!('message' in value)) return false;
    return true;
}

export function ChoiceFromJSON(json: any): Choice {
    return ChoiceFromJSONTyped(json, false);
}

export function ChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Choice {
    if (json == null) {
        return json;
    }
    return {
        
        'finishReason': FinishReasonFromJSON(json['finish_reason']),
        'index': json['index'],
        'message': ChatMessageFromJSON(json['message']),
    };
}

export function ChoiceToJSON(value?: Choice | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'finish_reason': FinishReasonToJSON(value['finishReason']),
        'index': value['index'],
        'message': ChatMessageToJSON(value['message']),
    };
}

