/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FinishReason = {
    Stop: 'stop',
    Length: 'length',
    ToolCalls: 'tool_calls',
    ContentFilter: 'content_filter',
    FunctionCall: 'function_call'
} as const;
export type FinishReason = typeof FinishReason[keyof typeof FinishReason];


export function instanceOfFinishReason(value: any): boolean {
    return Object.values(FinishReason).includes(value);
}

export function FinishReasonFromJSON(json: any): FinishReason {
    return FinishReasonFromJSONTyped(json, false);
}

export function FinishReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinishReason {
    return json as FinishReason;
}

export function FinishReasonToJSON(value?: FinishReason | null): any {
    return value as any;
}

